# Generated by Django 5.1.1 on 2024-12-27 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_todo_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='img',
        ),
        migrations.CreateModel(
            name='TodoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Blog.todo')),
            ],
        ),
    ]
