# Generated by Django 5.1.1 on 2024-12-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_remove_todo_img_todoimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoimage',
            old_name='image',
            new_name='img',
        ),
    ]
