# Generated by Django 5.1.1 on 2024-12-19 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
