# Generated by Django 5.1.1 on 2024-12-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_rename_image_todoimage_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoImage',
        ),
    ]
