# Generated by Django 5.1.1 on 2025-01-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_blogimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
